"""empty message

Revision ID: 64b5759d7fd8
Revises: 
Create Date: 2020-09-05 03:45:42.089619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64b5759d7fd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_table('player_full')
    op.drop_table('player')
    op.drop_table('match')
    op.drop_table('player_stats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('club', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('overall', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('finishing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('heading_accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('short_passing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('volleys', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dribbling', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('curve', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('long_passing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ball_control', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acceleration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sprint_speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agility', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reactions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shot_power', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jumping', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stamina', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('strength', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('long_shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aggression', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interceptions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('positioning', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vision', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalties', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('composure', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('marking', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('standing_tackle', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sliding_tackle', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='player_stats_pkey')
    )
    op.create_table('match',
    sa.Column('match_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('league', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('home_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('home_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('away_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('home_goals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_goals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_1_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_2_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_3_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_4_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_5_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_6_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_7_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_8_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_9_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_10_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_1_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_2_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_3_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_4_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_5_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_6_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_7_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_8_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_9_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_10_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('match_id', name='match_pkey')
    )
    op.create_table('player',
    sa.Column('player_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('player_id', name='player_pkey')
    )
    op.create_table('player_full',
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('club', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('overall', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('finishing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('heading_accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('short_passing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('volleys', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dribbling', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('curve', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('long_passing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ball_control', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acceleration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sprint_speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agility', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reactions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shot_power', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jumping', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stamina', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('strength', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('long_shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aggression', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interceptions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('positioning', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vision', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalties', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('composure', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('marking', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('standing_tackle', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sliding_tackle', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
