"""empty message

Revision ID: b7905a03fe0a
Revises: 64b5759d7fd8
Create Date: 2020-09-05 05:06:54.637679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7905a03fe0a'
down_revision = '64b5759d7fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('league', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('home_id', sa.Integer(), nullable=True),
    sa.Column('home_name', sa.String(length=50), nullable=True),
    sa.Column('away_id', sa.Integer(), nullable=True),
    sa.Column('away_name', sa.String(length=50), nullable=True),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Integer(), nullable=True),
    sa.Column('start_1_home', sa.Integer(), nullable=True),
    sa.Column('start_2_home', sa.Integer(), nullable=True),
    sa.Column('start_3_home', sa.Integer(), nullable=True),
    sa.Column('start_4_home', sa.Integer(), nullable=True),
    sa.Column('start_5_home', sa.Integer(), nullable=True),
    sa.Column('start_6_home', sa.Integer(), nullable=True),
    sa.Column('start_7_home', sa.Integer(), nullable=True),
    sa.Column('start_8_home', sa.Integer(), nullable=True),
    sa.Column('start_9_home', sa.Integer(), nullable=True),
    sa.Column('start_10_home', sa.Integer(), nullable=True),
    sa.Column('start_1_away', sa.Integer(), nullable=True),
    sa.Column('start_2_away', sa.Integer(), nullable=True),
    sa.Column('start_3_away', sa.Integer(), nullable=True),
    sa.Column('start_4_away', sa.Integer(), nullable=True),
    sa.Column('start_5_away', sa.Integer(), nullable=True),
    sa.Column('start_6_away', sa.Integer(), nullable=True),
    sa.Column('start_7_away', sa.Integer(), nullable=True),
    sa.Column('start_8_away', sa.Integer(), nullable=True),
    sa.Column('start_9_away', sa.Integer(), nullable=True),
    sa.Column('start_10_away', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('team', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('player_full',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('club', sa.String(length=50), nullable=True),
    sa.Column('overall', sa.Integer(), nullable=True),
    sa.Column('finishing', sa.Integer(), nullable=True),
    sa.Column('heading_accuracy', sa.Integer(), nullable=True),
    sa.Column('short_passing', sa.Integer(), nullable=True),
    sa.Column('volleys', sa.Integer(), nullable=True),
    sa.Column('dribbling', sa.Integer(), nullable=True),
    sa.Column('curve', sa.Integer(), nullable=True),
    sa.Column('fk_accuracy', sa.Integer(), nullable=True),
    sa.Column('long_passing', sa.Integer(), nullable=True),
    sa.Column('ball_control', sa.Integer(), nullable=True),
    sa.Column('acceleration', sa.Integer(), nullable=True),
    sa.Column('sprint_speed', sa.Integer(), nullable=True),
    sa.Column('agility', sa.Integer(), nullable=True),
    sa.Column('reactions', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('shot_power', sa.Integer(), nullable=True),
    sa.Column('jumping', sa.Integer(), nullable=True),
    sa.Column('stamina', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('long_shots', sa.Integer(), nullable=True),
    sa.Column('aggression', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('positioning', sa.Integer(), nullable=True),
    sa.Column('vision', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('composure', sa.Integer(), nullable=True),
    sa.Column('marking', sa.Integer(), nullable=True),
    sa.Column('standing_tackle', sa.Integer(), nullable=True),
    sa.Column('sliding_tackle', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('club', sa.String(length=50), nullable=True),
    sa.Column('overall', sa.Integer(), nullable=True),
    sa.Column('finishing', sa.Integer(), nullable=True),
    sa.Column('heading_accuracy', sa.Integer(), nullable=True),
    sa.Column('short_passing', sa.Integer(), nullable=True),
    sa.Column('volleys', sa.Integer(), nullable=True),
    sa.Column('dribbling', sa.Integer(), nullable=True),
    sa.Column('curve', sa.Integer(), nullable=True),
    sa.Column('fk_accuracy', sa.Integer(), nullable=True),
    sa.Column('long_passing', sa.Integer(), nullable=True),
    sa.Column('ball_control', sa.Integer(), nullable=True),
    sa.Column('acceleration', sa.Integer(), nullable=True),
    sa.Column('sprint_speed', sa.Integer(), nullable=True),
    sa.Column('agility', sa.Integer(), nullable=True),
    sa.Column('reactions', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('shot_power', sa.Integer(), nullable=True),
    sa.Column('jumping', sa.Integer(), nullable=True),
    sa.Column('stamina', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('long_shots', sa.Integer(), nullable=True),
    sa.Column('aggression', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('positioning', sa.Integer(), nullable=True),
    sa.Column('vision', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('composure', sa.Integer(), nullable=True),
    sa.Column('marking', sa.Integer(), nullable=True),
    sa.Column('standing_tackle', sa.Integer(), nullable=True),
    sa.Column('sliding_tackle', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    op.drop_table('player_full')
    op.drop_table('player')
    op.drop_table('match')
    # ### end Alembic commands ###
