"""clean database

Revision ID: e28898ac45f1
Revises: b7905a03fe0a
Create Date: 2020-09-14 03:21:20.977039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e28898ac45f1'
down_revision = 'b7905a03fe0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    op.drop_table('player')
    op.drop_table('player_1819')
    op.drop_table('match')
    op.drop_table('player_full')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_full',
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('club', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('club_short', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('overall', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('finishing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('heading_accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('short_passing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('volleys', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dribbling', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('curve', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('long_passing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ball_control', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acceleration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sprint_speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agility', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reactions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shot_power', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jumping', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stamina', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('strength', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('long_shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aggression', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interceptions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('positioning', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vision', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalties', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('composure', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('marking', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('standing_tackle', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sliding_tackle', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('match',
    sa.Column('match_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('league', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('home_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('home_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('away_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('home_goals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_goals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_1_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_2_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_3_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_4_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_5_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_6_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_7_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_8_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_9_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_10_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_1_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_2_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_3_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_4_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_5_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_6_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_7_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_8_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_9_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_10_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('match_id', name='match_pkey')
    )
    op.create_table('player_1819',
    sa.Column('fifa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crossing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('finishing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('headingAccuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shortPassing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('volleys', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dribbling', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('curve', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fkAccuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('longPassing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ballControl', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acceleration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sprintSpeed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agility', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reactions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shotPower', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jumping', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stamina', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('strength', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('longShots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aggression', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interceptions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('positioning', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vision', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalties', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('composure', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('defensiveAwareness', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('standingTackle', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('slidingTackle', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gkDiving', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gkHandling', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gkKicking', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gkPositioning', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gkReflexes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('fifa_id', name='player_1819_pkey')
    )
    op.create_table('player',
    sa.Column('player_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('player_id', name='player_pkey')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('club', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('club_short', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('overall', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('finishing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('heading_accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('short_passing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('volleys', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dribbling', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('curve', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('long_passing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ball_control', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acceleration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sprint_speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agility', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reactions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shot_power', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jumping', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stamina', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('strength', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('long_shots', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aggression', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interceptions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('positioning', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vision', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('penalties', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('composure', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('marking', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('standing_tackle', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sliding_tackle', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='player_stats_pkey')
    )
    # ### end Alembic commands ###
